
-- 1. EXTENSIONS
create extension if not exists "uuid-ossp";

-- 2. TABLE DES PROFILS UTILISATEURS
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  role text,
  authority text,
  parent_ministry text,
  status text default 'Inactive',
  last_login timestamptz,
  created_at timestamptz default now()
);

-- 3. TABLE DES PROJETS
create table if not exists public.projects (
  id text primary key,
  title text,
  description text,
  sector text,
  location text,
  status text,
  contracting_authority text,
  parent_ministry text,
  
  -- Financier
  capex_total numeric default 0,
  opex numeric default 0,
  total_cost numeric default 0,
  public_contribution_capex numeric default 0,
  private_contribution_capex numeric default 0,
  public_contribution_opex numeric default 0,
  private_contribution_opex numeric default 0,
  estimated_revenue text,
  remuneration_mode text,
  
  -- Technique
  alignment text,
  priority_degree text,
  purpose text,
  expected_results text,
  activities text,
  contractual_form text,
  duration_years integer,
  ppp_justification text,
  gps_coordinates text,
  impact_zone text,
  legal_framework text,
  related_projects text,
  private_partner text,
  development_stage text,
  next_step text,
  contact_person text,
  
  progress integer default 0,
  documents jsonb default '[]'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 4. TABLE DES VISAS (Workflow)
create table if not exists public.approval_logs (
  id bigint generated by default as identity primary key,
  project_id text references public.projects(id) ON DELETE CASCADE,
  action text,
  comment text,
  new_status text,
  actor_id text,
  created_at timestamptz default now()
);

-- 5. SECURITE (RLS)
alter table public.profiles enable row level security;
alter table public.projects enable row level security;
alter table public.approval_logs enable row level security;

-- POLITIQUES PERMISSIVES (CORRIGÉES POUR L'ADMINISTRATION)
-- Suppression des anciennes politiques restrictives si nécessaire (à faire manuellement si conflit)
-- Ici on définit des droits larges pour les utilisateurs connectés afin de faciliter le prototype
create policy "Tout le monde peut voir les profils" on profiles for select using (true);
create policy "Modification profils authentifiés" on profiles for update using (auth.role() = 'authenticated');
create policy "Insertion profil système" on profiles for insert with check (auth.uid() = id);
create policy "Suppression profils authentifiés" on profiles for delete using (auth.role() = 'authenticated');

create policy "Lecture publique projets" on projects for select using (true);
create policy "Modification projets authentifiés" on projects for all using (auth.role() = 'authenticated');

create policy "Lecture publique logs" on approval_logs for select using (true);
create policy "Ecriture logs authentifiés" on approval_logs for insert with check (auth.role() = 'authenticated');
